version: "3.9"
services:
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_DB: "symfony"
            POSTGRES_USER: "symfony"
            POSTGRES_PASSWORD: "symfony"
        ports:
            - "5432:5432"


